### ISSUE TITLE
znalezienie dokumentacji technicznej przydatnej dla naszego projektu (moduly czujnikow oraz arduino) KM KJ

### ISSUE THREAD

**Issue by hnr015** [Swagrzyk/doniczka#8]
**Arduino** (https://docs.arduino.cc/)

**Pompa wody** (https://botland.com.pl/pompy/14164-pompa-wodna-6v-5904422342401.html): 
https://www.seeedstudio.com/document/pics/6V%20Mini%20Water%20Pump.jpg

**Czujnik poziomu cieczy** (https://botland.com.pl/czujniki-poziomu-cieczy/7279-czujnik-poziomu-cieczy-analogowy-iduino-se045-5903351241281.html): 
https://www.learningaboutelectronics.com/Articles/Arduino-liquid-level-sensor-circuit.php // przykład kodu i podłączenia do Arduino

**Czujnik wilgotności gleby** (https://botland.com.pl/czujniki-wilgotnosci/1588-czujnik-wilgotnosci-gleby-5904422368289.html): 
https://wiki.dfrobot.com/Moisture_Sensor__SKU_SEN0114_  // przykład kodu i podłączenia do Arduino
https://botland.com.pl/content/150-arduino-w-polaczeniu-z-czujnikiem-wilgotnosci // przykład kodu i podłączenia do Arduino

**ESP32** (https://botland.com.pl/moduly-wifi-i-bt-esp32/8893-esp32-wifi-bt-42-platforma-z-modulem-esp-wroom-32-zgodny-z-esp32-devkit-5904422337438.html): 
https://botland.com.pl/index.php?controller=attachment&id_attachment=1810 // dokumentacja techniczna
https://www.dfrobot.com/blog-598.html // dodanie ESP32 do Arduino

**RTC zegar** (https://botland.com.pl/moduly-rtc/12507-rtc-ds1307-32kb-eeprom-24c32-i2c-zegar-czasu-rzeczywistego-z-pamiecia-5904422341121.html): 
https://botland.com.pl/index.php?controller=attachment&id_attachment=416 // dokumentacja techniczna
https://github.com/turicas/DS1307/ // biblioteka

**Sterownik silnika krokowego L9110** (https://botland.com.pl/sterowniki-silnikow-krokowych/9820-sterownik-silnika-krokowego-l9110-12v08a-5904422338442.html): 
https://www.bananarobotics.com/shop/How-to-use-the-HG7881-(L9110)-Dual-Channel-Motor-Driver-Module // przykładowy kod

**Comment by Swagrzyk** [comment]
git
